### ISSUE TITLE
GHC 9.0 Compatibility

### ISSUE THREAD

**Issue by sheepforce** [hackage-trustees/PSQueue#1]
Would it be possible to raise the upper bounds of base to make it compatible with GHC 9.0? As far as I see there should be no problems.

**Comment by phadej** [comment]
I'd be happy if someone else (i.e. non-trustee) took over maintenance of `PSQueue`.

EDIT: it has been at least two years without a maintainer, so IMO it is up for grabs.

**Comment by TeofilC** [comment]
I'd be interested in taking over maintenance.

**Comment by phadej** [comment]
@TeofilC thanks for stepping up. I'll close this issue.
